AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CD Demo Lambda
Resources:
  CDDemoLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./Lambda
      Description: 'Lambda function for CD Demo'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::706374939365:role/MyLambdaRole'
      Events:
        helloAPI:
          Type: Api
          Properties:
            Path: /hello
            Method: get
      Environment:
        Variables:
          REGION: ap-south-1
  